Update plugins

diff --git a/mod/choicegroup/.github/workflows/moodle-plugin-ci.yml b/mod/choicegroup/.github/workflows/moodle-plugin-ci.yml
--- a/mod/choicegroup/.github/workflows/moodle-plugin-ci.yml
+++ b/mod/choicegroup/.github/workflows/moodle-plugin-ci.yml
@@ -16,12 +16,10 @@ jobs:
           - 5432:5432
         options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
       mariadb:
-        image: mariadb:10.6
+        image: mariadb:10
         env:
           MYSQL_USER: 'root'
           MYSQL_ALLOW_EMPTY_PASSWORD: "true"
-          MYSQL_CHARACTER_SET_SERVER: "utf8mb4"
-          MYSQL_COLLATION_SERVER: "utf8mb4_unicode_ci"
         ports:
           - 3306:3306
         options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3
@@ -29,65 +27,13 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        include:
-          - php: '8.1'
-            moodle-branch: 'MOODLE_405_STABLE'
-            database: pgsql
-          - php: '8.2'
-            moodle-branch: 'MOODLE_405_STABLE'
-            database: pgsql
-          - php: '8.3'
-            moodle-branch: 'MOODLE_405_STABLE'
-            database: pgsql
-          - php: '8.1'
-            moodle-branch: 'MOODLE_405_STABLE'
-            database: mariadb
-          - php: '8.2'
-            moodle-branch: 'MOODLE_405_STABLE'
-            database: mariadb
-          - php: '8.3'
-            moodle-branch: 'MOODLE_405_STABLE'
-            database: mariadb
-          - php: '8.1'
-            moodle-branch: 'MOODLE_404_STABLE'
-            database: pgsql
-          - php: '8.2'
-            moodle-branch: 'MOODLE_404_STABLE'
-            database: pgsql
-          - php: '8.3'
-            moodle-branch: 'MOODLE_404_STABLE'
-            database: pgsql
-          - php: '8.1'
-            moodle-branch: 'MOODLE_404_STABLE'
-            database: mariadb
-          - php: '8.2'
-            moodle-branch: 'MOODLE_404_STABLE'
-            database: mariadb
-          - php: '8.3'
-            moodle-branch: 'MOODLE_404_STABLE'
-            database: mariadb
-          - php: '8.0'
-            moodle-branch: 'MOODLE_403_STABLE'
-            database: pgsql
-          - php: '8.1'
-            moodle-branch: 'MOODLE_403_STABLE'
-            database: pgsql
-          - php: '8.2'
-            moodle-branch: 'MOODLE_403_STABLE'
-            database: pgsql
-          - php: '8.0'
-            moodle-branch: 'MOODLE_403_STABLE'
-            database: mariadb
-          - php: '8.1'
-            moodle-branch: 'MOODLE_403_STABLE'
-            database: mariadb
-          - php: '8.2'
-            moodle-branch: 'MOODLE_403_STABLE'
-            database: mariadb
+        php: ['8.1', '8.2']
+        moodle-branch: ['MOODLE_402_STABLE', 'MOODLE_403_STABLE', 'MOODLE_404_STABLE']
+        database: [pgsql, mariadb]
 
     steps:
       - name: Check out repository code
-        uses: actions/checkout@v4
+        uses: actions/checkout@v3
         with:
           path: plugin
 
@@ -101,7 +47,7 @@ jobs:
 
       - name: Initialise moodle-plugin-ci
         run: |
-          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
+          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
           echo $(cd ci/bin; pwd) >> $GITHUB_PATH
           echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
           sudo locale-gen en_AU.UTF-8
@@ -118,6 +64,11 @@ jobs:
         if: ${{ always() }}
         run: moodle-plugin-ci phplint
 
+      - name: PHP Copy/Paste Detector
+        continue-on-error: true # This step will show errors but will not fail
+        if: ${{ always() }}
+        run: moodle-plugin-ci phpcpd || true
+
       - name: PHP Mess Detector
         continue-on-error: true # This step will show errors but will not fail
         if: ${{ always() }}
@@ -125,20 +76,32 @@ jobs:
 
       - name: Moodle Code Checker
         if: ${{ always() }}
-        run: moodle-plugin-ci codechecker --max-warnings 0
+        run: moodle-plugin-ci codechecker || true
 
       - name: Moodle PHPDoc Checker
         if: ${{ always() }}
-        run: moodle-plugin-ci phpdoc
+        run: moodle-plugin-ci phpdoc || true
 
       - name: Validating
         if: ${{ always() }}
         run: moodle-plugin-ci validate
 
+      - name: Check upgrade savepoints
+        if: ${{ always() }}
+        run: moodle-plugin-ci savepoints || true
+
+      - name: Mustache Lint
+        if: ${{ always() }}
+        run: moodle-plugin-ci mustache || true
+
+      - name: Grunt
+        if: ${{ always() }}
+        run: moodle-plugin-ci grunt
+
       - name: PHPUnit tests
         if: ${{ always() }}
-        run: moodle-plugin-ci phpunit --fail-on-warning
+        run: moodle-plugin-ci phpunit
 
       - name: Behat features
         if: ${{ always() }}
-        run: moodle-plugin-ci behat --profile chrome --auto-rerun 0
+        run: moodle-plugin-ci behat --profile chrome
